// mes/vue3/src/views/workflow/definition/AssociateFormDialog.vue
<template>
  <FormDialog
    :model-value="modelValue"
    title="关联流程表单"
    width="480px"
    :loading="submitLoading"
    @update:model-value="(v) => emit('update:modelValue', v)"
    @submit="handleSubmit"
  >
    <el-form label-width="92px">
      <el-form-item label="流程">
        <span>{{ definition?.processName }}</span>
      </el-form-item>
      <el-form-item label="关联表单">
        <el-select v-model="selected" :loading="loading" style="width: 100%">
          <el-option label="未关联" :value="NONE" />
          <el-option
            v-for="f in forms"
            :key="f.formKey"
            :label="`${f.name} (${f.formKey})`"
            :value="f.formKey"
          />
        </el-select>
      </el-form-item>
    </el-form>
  </FormDialog>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue'
import { ElMessage } from 'element-plus'
import FormDialog from '@/components/FormDialog.vue'
import { formList } from '@/api/workflow/form'
import { definitionSetForm } from '@/api/workflow/definition'
import type { WorkflowForm, WorkflowDefinition } from '@/types/workflow'

const NONE = '__none__'

const props = defineProps<{
  modelValue: boolean
  definition: WorkflowDefinition | null
}>()

const emit = defineEmits<{
  'update:modelValue': [boolean]
  saved: []
}>()

const forms = ref<WorkflowForm[]>([])
const loading = ref(false)
const submitLoading = ref(false)
const selected = ref<string>(NONE)

watch(
  () => props.modelValue,
  async (open) => {
    if (!open) return
    selected.value = props.definition?.formKey || NONE
    loading.value = true
    try {
      forms.value = await formList()
    } finally {
      loading.value = false
    }
  },
)

async function handleSubmit() {
  if (!props.definition) return
  submitLoading.value = true
  try {
    const formKey = selected.value === NONE ? null : selected.value
    await definitionSetForm(props.definition.id, formKey)
    ElMessage.success('保存成功')
    emit('update:modelValue', false)
    emit('saved')
  } finally {
    submitLoading.value = false
  }
}
</script>

// mes/frontend/apps/mes-new/src/pages/workflow/definition/AssociateFormDialog.tsx
import { useEffect, useState } from 'react'
import {
  Button,
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
  toast,
} from '@workspace/ui'
import { useQuery$, useMutation$ } from '@/http/hooks'
import { invalidate } from '@/http/queryCache'
import { formList } from '@/api/workflow/form'
import { definitionSetForm } from '@/api/workflow/definition'
import type { WorkflowDefinition } from '@/types/workflow'

interface AssociateFormDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  definition: WorkflowDefinition | null
}

const NONE = '__none__'

export default function AssociateFormDialog({ open, onOpenChange, definition }: AssociateFormDialogProps) {
  const { data: forms } = useQuery$(['workflow', 'form', 'all'], () => formList(), { enabled: open })
  const { mutate, loading } = useMutation$((arg: { id: string; formKey: string | null }) =>
    definitionSetForm(arg.id, arg.formKey),
  )
  const [selected, setSelected] = useState<string>(NONE)

  useEffect(() => {
    if (open) setSelected(definition?.formKey ?? NONE)
  }, [open, definition])

  const onSave = async () => {
    if (!definition) return
    try {
      await mutate({ id: definition.id, formKey: selected === NONE ? null : selected })
      toast.success('关联已更新')
      invalidate('["workflow","definition"')
      onOpenChange(false)
    } catch {
      /* 拦截器已 toast */
    }
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>关联流程表单</DialogTitle>
          <DialogDescription>为「{definition?.processName}」选择一个流程表单(按 key)。</DialogDescription>
        </DialogHeader>
        <Select value={selected} onValueChange={setSelected}>
          <SelectTrigger className="w-full">
            <SelectValue placeholder="选择流程表单" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value={NONE}>未关联</SelectItem>
            {(forms ?? []).map((f) => (
              <SelectItem key={f.id} value={f.formKey}>
                {f.name}（{f.formKey}）
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)}>
            取消
          </Button>
          <Button onClick={onSave} disabled={loading}>
            {loading ? '保存中…' : '保存'}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
