// mes/vue3/src/views/workflow/definition/DefinitionList.vue
<template>
  <PageContainer>
    <SearchForm :model="search" @search="handleSearch" @reset="handleReset">
      <el-form-item label="流程名称">
        <el-input v-model="search.name" placeholder="请输入流程名称" clearable />
      </el-form-item>
    </SearchForm>

    <DataTable
      :data="tableData"
      :loading="loading"
      :columns="columns"
      :pager="pager"
      :action-width="240"
      @page-change="handlePageChange"
      @size-change="handleSizeChange"
    >
      <template #col-version="{ row }">v{{ row.version }}</template>
      <template #col-enabled="{ row }">
        <el-tag size="small" :type="row.enabled ? 'success' : 'info'">
          {{ row.enabled ? '启用' : '停用' }}
        </el-tag>
      </template>
      <template #col-formKey="{ row }">
        <el-tag v-if="row.formKey" size="small" type="warning">{{ row.formKey }}</el-tag>
        <span v-else class="muted">未关联</span>
      </template>

      <template #actions="{ row }">
        <el-button type="primary" link size="small" @click="toggleEnabled(row as WorkflowDefinition)">
          {{ (row as WorkflowDefinition).enabled ? '停用' : '启用' }}
        </el-button>
        <el-button type="primary" link size="small" @click="openAssociate(row as WorkflowDefinition)">关联表单</el-button>
        <el-button type="primary" link size="small" @click="openEvents(row as WorkflowDefinition)">流程事件</el-button>
      </template>
    </DataTable>

    <AssociateFormDialog v-model="associateVisible" :definition="activeDef" @saved="run" />
    <EventConfigDialog v-model="eventVisible" :definition="activeDef" />
  </PageContainer>
</template>

<script setup lang="ts">
import { ref, reactive, computed } from 'vue'
import { ElMessage } from 'element-plus'
import PageContainer from '@/components/PageContainer.vue'
import SearchForm from '@/components/SearchForm.vue'
import DataTable from '@/components/DataTable.vue'
import type { Column } from '@/components/DataTable.vue'
import AssociateFormDialog from './AssociateFormDialog.vue'
import EventConfigDialog from './EventConfigDialog.vue'
import { useRequest } from '@/composables/useRequest'
import { usePagination } from '@/composables/usePagination'
import { definitionPage, definitionSetEnabled } from '@/api/workflow/definition'
import type { WorkflowDefinition } from '@/types/workflow'

const { pager, setTotal, reset } = usePagination()
const search = reactive({ name: '' })

const { data: pageData, loading, run } = useRequest(
  () => definitionPage({ current: pager.current, size: pager.size, ...search }),
  { immediate: true },
)

const tableData = computed<WorkflowDefinition[]>(() => {
  const result = pageData.value
  if (result) setTotal(result.total)
  return result?.records ?? []
})

const columns: Column[] = [
  { prop: 'processName', label: '流程名称', minWidth: 160 },
  { prop: 'processKey', label: 'processKey', width: 160 },
  { prop: 'categoryName', label: '分类', width: 130 },
  { prop: 'version', label: '版本', width: 80 },
  { prop: 'enabled', label: '状态', width: 90 },
  { prop: 'formKey', label: '关联表单', width: 150 },
]

const associateVisible = ref(false)
const eventVisible = ref(false)
const activeDef = ref<WorkflowDefinition | null>(null)

function openAssociate(row: WorkflowDefinition) {
  activeDef.value = row
  associateVisible.value = true
}
function openEvents(row: WorkflowDefinition) {
  activeDef.value = row
  eventVisible.value = true
}

async function toggleEnabled(row: WorkflowDefinition) {
  try {
    await definitionSetEnabled(row.id, !row.enabled)
    ElMessage.success(row.enabled ? '已停用' : '已启用')
    run()
  } catch { /* 响应拦截器已提示 */ }
}

function handlePageChange(page: number) {
  pager.current = page
  run()
}
function handleSizeChange(size: number) {
  pager.size = size
  reset()
  run()
}
function handleSearch() {
  reset()
  run()
}
function handleReset() {
  search.name = ''
  reset()
  run()
}
</script>

<style scoped>
.muted {
  color: var(--el-text-color-secondary);
}
</style>

// mes/frontend/apps/mes-new/src/pages/workflow/definition/DefinitionList.tsx
import { useMemo, useState } from 'react'
import type { ColumnDef } from '@tanstack/react-table'
import { Badge, Button, DataTable, Input, Label, toast } from '@workspace/ui'
import { FileText, Power, Workflow } from 'lucide-react'
import PageContainer from '@/components/PageContainer'
import SearchForm from '@/components/SearchForm'
import AssociateFormDialog from './AssociateFormDialog'
import EventConfigDialog from './EventConfigDialog'
import { useQuery$, useMutation$ } from '@/http/hooks'
import { invalidate } from '@/http/queryCache'
import { definitionPage, definitionSetEnabled, type DefinitionPageParams } from '@/api/workflow/definition'
import type { WorkflowDefinition } from '@/types/workflow'

const PAGE_SIZE = 10

export default function DefinitionList() {
  const [params, setParams] = useState<DefinitionPageParams>({ current: 1, size: PAGE_SIZE })
  const [draftName, setDraftName] = useState('')
  const [associating, setAssociating] = useState<WorkflowDefinition | null>(null)
  const [eventing, setEventing] = useState<WorkflowDefinition | null>(null)

  const { data, loading } = useQuery$(['workflow', 'definition', 'page', params], () => definitionPage(params))
  const { mutate: toggleEnabled } = useMutation$((arg: { id: string; enabled: boolean }) =>
    definitionSetEnabled(arg.id, arg.enabled),
  )

  const onSearch = () => setParams({ current: 1, size: PAGE_SIZE, name: draftName || undefined })
  const onReset = () => {
    setDraftName('')
    setParams({ current: 1, size: PAGE_SIZE })
  }

  const onToggle = async (d: WorkflowDefinition) => {
    try {
      await toggleEnabled({ id: d.id, enabled: !d.enabled })
      toast.success(d.enabled ? '已停用' : '已启用')
      invalidate('["workflow","definition"')
    } catch {
      /* 拦截器已 toast */
    }
  }

  const columns = useMemo<ColumnDef<WorkflowDefinition>[]>(
    () => [
      { accessorKey: 'processName', header: '流程名称' },
      { accessorKey: 'processKey', header: 'processKey' },
      { id: 'category', header: '分类', cell: ({ row }) => row.original.categoryName || '-' },
      { id: 'version', header: '版本', cell: ({ row }) => `v${row.original.version}` },
      {
        id: 'enabled',
        header: '状态',
        cell: ({ row }) =>
          row.original.enabled ? <Badge>启用</Badge> : <Badge variant="secondary">停用</Badge>,
      },
      {
        id: 'formKey',
        header: '关联表单',
        cell: ({ row }) =>
          row.original.formKey ? (
            <Badge variant="outline">{row.original.formKey}</Badge>
          ) : (
            <span className="text-muted-foreground">未关联</span>
          ),
      },
      {
        id: 'actions',
        header: '操作',
        cell: ({ row }) => (
          <div className="flex gap-1">
            <Button variant="ghost" size="sm" onClick={() => onToggle(row.original)}>
              <Power className="size-4" />
              {row.original.enabled ? '停用' : '启用'}
            </Button>
            <Button variant="ghost" size="sm" onClick={() => setAssociating(row.original)}>
              <FileText className="size-4" />
              关联表单
            </Button>
            <Button variant="ghost" size="sm" onClick={() => setEventing(row.original)}>
              <Workflow className="size-4" />
              流程事件
            </Button>
          </div>
        ),
      },
    ],
    // onToggle 用到的 mutate 引用稳定,空依赖可接受(对齐 CategoryList 列定义风格)
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [],
  )

  return (
    <PageContainer title="流程定义管理" description="已发布流程定义:启用停用、关联表单、配置流程事件">
      <div className="space-y-3">
        <SearchForm onSearch={onSearch} onReset={onReset}>
          <div className="space-y-1.5">
            <Label htmlFor="wd-s-name">流程名称</Label>
            <Input id="wd-s-name" className="h-9 w-40" value={draftName} onChange={(e) => setDraftName(e.target.value)} />
          </div>
        </SearchForm>
        <DataTable
          columns={columns}
          data={data?.records ?? []}
          loading={loading}
          loadingRowCount={PAGE_SIZE}
          getRowId={(r) => r.id}
          pagination={{
            mode: 'server',
            pageIndex: (data?.current ?? params.current) - 1,
            pageSize: PAGE_SIZE,
            totalPages: data?.pages ?? 1,
            totalRows: data?.total,
            onPageChange: (idx) => setParams((p) => ({ ...p, current: idx + 1 })),
          }}
        />
      </div>

      <AssociateFormDialog open={!!associating} onOpenChange={(o) => !o && setAssociating(null)} definition={associating} />
      <EventConfigDialog open={!!eventing} onOpenChange={(o) => !o && setEventing(null)} definition={eventing} />
    </PageContainer>
  )
}
