// mes/vue3/src/views/workflow/model/PropertiesPanel.vue
<template>
  <div v-if="!element" class="pp pp--empty">请选择左侧节点进行配置</div>
  <div v-else class="pp">
    <div class="pp__head">
      <p class="pp__title">节点属性</p>
      <p class="pp__type">{{ element.type }}</p>
    </div>

    <div class="pp__field">
      <label class="pp__label">节点名称</label>
      <el-input v-model="name" placeholder="节点名称" @blur="emit('changeName', name)" />
    </div>

    <template v-if="isUserTask">
      <div class="pp__field">
        <label class="pp__label">办理人</label>
        <el-radio-group v-model="assigneeType" @change="onTypeChange">
          <el-radio value="initiator">流程发起人</el-radio>
          <el-radio value="candidate">候选组(按角色)</el-radio>
        </el-radio-group>
      </div>
      <div v-if="assigneeType === 'candidate'" class="pp__field">
        <label class="pp__label">角色</label>
        <el-select v-model="roleCode" placeholder="选择角色" style="width: 100%" @change="onRoleChange">
          <el-option v-for="r in roles" :key="r.id" :label="r.name" :value="r.code" />
        </el-select>
      </div>
    </template>
    <p v-else class="pp__hint">该节点无需配置办理人</p>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import type { SelectedElement, AssigneeType } from '@/utils/bpmn'
import type { SysRole } from '@/types/system'

const props = defineProps<{
  element: SelectedElement | null
  roles: SysRole[]
}>()

const emit = defineEmits<{
  changeName: [string]
  changeAssignee: [AssigneeType, string?]
}>()

const name = ref('')
const assigneeType = ref<AssigneeType>('initiator')
const roleCode = ref('')

const isUserTask = computed(() => props.element?.type === 'bpmn:UserTask')

function deriveType(el: SelectedElement | null): AssigneeType {
  return el?.candidateGroups ? 'candidate' : 'initiator'
}

// 选中元素变化时同步本地受控态
watch(
  () => props.element,
  (el) => {
    name.value = el?.name ?? ''
    assigneeType.value = deriveType(el)
    roleCode.value = el?.candidateGroups ?? ''
  },
  { immediate: true },
)

function onTypeChange(v: string | number | boolean | undefined) {
  const t = v as AssigneeType
  emit('changeAssignee', t, t === 'candidate' ? roleCode.value || undefined : undefined)
}
function onRoleChange(v: string) {
  emit('changeAssignee', 'candidate', v)
}
</script>

<style scoped>
.pp {
  display: flex;
  flex-direction: column;
  gap: 18px;
  padding: 16px;
}
.pp--empty {
  color: var(--el-text-color-secondary);
  font-size: 14px;
}
.pp__title {
  font-size: 12px;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: var(--el-text-color-secondary);
  margin: 0;
}
.pp__type {
  margin: 4px 0 0;
  font-size: 12px;
  color: var(--el-text-color-secondary);
}
.pp__field {
  display: flex;
  flex-direction: column;
  gap: 6px;
}
.pp__label {
  font-size: 13px;
  font-weight: 500;
}
.pp__hint {
  font-size: 12px;
  color: var(--el-text-color-secondary);
}
</style>

// mes/frontend/apps/mes-new/src/pages/workflow/model/PropertiesPanel.tsx
import { useEffect, useState } from 'react'
import {
  Input,
  Label,
  RadioGroup,
  RadioGroupItem,
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@workspace/ui'
import type { SelectedElement } from './BpmnDesigner'
import type { AssigneeType } from './bpmnUtils'
import type { SysRole } from '@/types/system'

interface PropertiesPanelProps {
  element: SelectedElement | null
  roles: SysRole[]
  onChangeName: (name: string) => void
  onChangeAssignee: (type: AssigneeType, roleCode?: string) => void
}

function deriveType(el: SelectedElement | null): AssigneeType {
  if (el?.candidateGroups) return 'candidate'
  return 'initiator'
}

export default function PropertiesPanel({
  element,
  roles,
  onChangeName,
  onChangeAssignee,
}: PropertiesPanelProps) {
  const [name, setName] = useState('')
  const [assigneeType, setAssigneeType] = useState<AssigneeType>('initiator')
  const [roleCode, setRoleCode] = useState<string>('')

  // 选中元素变化时同步本地受控态
  useEffect(() => {
    setName(element?.name ?? '')
    setAssigneeType(deriveType(element))
    setRoleCode(element?.candidateGroups ?? '')
  }, [element])

  if (!element) {
    return (
      <div className="p-4 text-sm text-muted-foreground">请选择左侧节点进行配置</div>
    )
  }

  const isUserTask = element.type === 'bpmn:UserTask'

  return (
    <div className="space-y-5 p-4">
      <div>
        <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
          节点属性
        </p>
        <p className="mt-1 text-xs text-muted-foreground">{element.type}</p>
      </div>

      <div className="space-y-1.5">
        <Label htmlFor="pp-name">节点名称</Label>
        <Input
          id="pp-name"
          value={name}
          onChange={(e) => setName(e.target.value)}
          onBlur={() => onChangeName(name)}
        />
      </div>

      {isUserTask ? (
        <div className="space-y-3">
          <Label>办理人</Label>
          <RadioGroup
            value={assigneeType}
            onValueChange={(v) => {
              const t = v as AssigneeType
              setAssigneeType(t)
              onChangeAssignee(t, t === 'candidate' ? roleCode || undefined : undefined)
            }}
          >
            <label className="flex items-center gap-2 text-sm">
              <RadioGroupItem value="initiator" id="pp-initiator" />
              流程发起人
            </label>
            <label className="flex items-center gap-2 text-sm">
              <RadioGroupItem value="candidate" id="pp-candidate" />
              候选组(按角色)
            </label>
          </RadioGroup>

          {assigneeType === 'candidate' && (
            <div className="space-y-1.5">
              <Label htmlFor="pp-role">生产主管角色</Label>
              <Select
                value={roleCode}
                onValueChange={(v) => {
                  setRoleCode(v)
                  onChangeAssignee('candidate', v)
                }}
              >
                <SelectTrigger id="pp-role">
                  <SelectValue placeholder="选择角色" />
                </SelectTrigger>
                <SelectContent>
                  {roles.map((r) => (
                    <SelectItem key={r.id} value={r.code}>
                      {r.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          )}
        </div>
      ) : (
        <p className="text-xs text-muted-foreground">该节点无需配置办理人</p>
      )}
    </div>
  )
}
