// mes/vue3/src/views/technology/oper/OperList.vue
<template>
  <PageContainer>
    <SearchForm :model="search" @search="handleSearch" @reset="handleReset">
      <el-form-item label="工序描述">
        <el-input v-model="search.operDescLike" placeholder="请输入工序描述" clearable />
      </el-form-item>
    </SearchForm>

    <DataTable
      :data="tableData"
      :loading="loading"
      :columns="columns"
      :pager="pager"
      @page-change="handlePageChange"
      @size-change="handleSizeChange"
    >
      <template #toolbar>
        <el-button v-permission="'oper:list'" type="primary" :icon="Plus" @click="openCreate">新增</el-button>
      </template>

      <template #col-generatePlan="{ row }">
        <el-tag size="small" :type="row.generatePlan === '1' ? 'success' : 'info'">
          {{ row.generatePlan === '1' ? '是' : '否' }}
        </el-tag>
      </template>

      <template #actions="{ row }">
        <el-button type="primary" link size="small" @click="openEdit(row as SpOper)">编辑</el-button>
        <el-button type="danger" link size="small" @click="handleDelete(row as SpOper)">删除</el-button>
      </template>
    </DataTable>

    <OperForm
      v-model="dialogVisible"
      :model="editingModel"
      :loading="submitLoading"
      @submit="handleFormSubmit"
    />
  </PageContainer>
</template>

<script setup lang="ts">
import { ref, reactive, computed } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Plus } from '@element-plus/icons-vue'
import PageContainer from '@/components/PageContainer.vue'
import SearchForm from '@/components/SearchForm.vue'
import DataTable, { type Column } from '@/components/DataTable.vue'
import OperForm from './OperForm.vue'
import { useRequest } from '@/composables/useRequest'
import { usePagination } from '@/composables/usePagination'
import { operPage, operAddOrUpdate, operDelete } from '@/api/technology/oper'
import type { SpOper } from '@/types/technology'

const { pager, setTotal, reset } = usePagination()
const search = reactive({ operDescLike: '' })

const { data: pageData, loading, run } = useRequest(
  () => operPage({ current: pager.current, size: pager.size, ...search }),
  { immediate: true },
)

const tableData = computed<SpOper[]>(() => {
  const result = pageData.value
  if (result) setTotal(result.total)
  return result?.records ?? []
})

const columns: Column[] = [
  { prop: 'operCode', label: '工序编码', width: 130 },
  { prop: 'operDesc', label: '工序描述', minWidth: 160 },
  { prop: 'laborHours', label: '工时(分)', width: 100 },
  { prop: 'manufacturingCycle', label: '制造周期(分)', width: 120 },
  { prop: 'generatePlan', label: '生成计划', width: 100 },
  { prop: 'remark', label: '备注', minWidth: 120 },
  { prop: 'createTime', label: '创建时间', minWidth: 160 },
]

const dialogVisible = ref(false)
const editingModel = ref<Partial<SpOper> | null>(null)
const submitLoading = ref(false)

function openCreate() {
  editingModel.value = null
  dialogVisible.value = true
}
function openEdit(row: SpOper) {
  editingModel.value = { ...row }
  dialogVisible.value = true
}

function handlePageChange(page: number) {
  pager.current = page
  run()
}
function handleSizeChange(size: number) {
  pager.size = size
  reset()
  run()
}
function handleSearch() {
  reset()
  run()
}
function handleReset() {
  search.operDescLike = ''
  reset()
  run()
}

async function handleFormSubmit(dto: Partial<SpOper>) {
  submitLoading.value = true
  try {
    await operAddOrUpdate(dto)
    ElMessage.success('保存成功')
    dialogVisible.value = false
    run()
  } finally {
    submitLoading.value = false
  }
}

async function handleDelete(row: SpOper) {
  try {
    await ElMessageBox.confirm(`确认删除工序「${row.operDesc}」?`, '提示', {
      type: 'warning',
      confirmButtonText: '确认删除',
      cancelButtonText: '取消',
    })
  } catch {
    return
  }
  try {
    await operDelete(row.id)
    ElMessage.success('删除成功')
    run()
  } catch { /* 响应拦截器已提示(含「被引用拒删」后端文案) */ }
}
</script>

// mes/frontend/src/pages/technology/OperList.tsx
import { useState } from 'react'
import { Form, Button, Input, Tag, Popconfirm, message } from 'antd'
import { PlusOutlined } from '@ant-design/icons'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import PageContainer from '@/components/PageContainer'
import { ensureArray } from '@/utils/ensureArray'
import SearchForm from '@/components/SearchForm'
import PageTable from '@/components/PageTable'
import ModalForm from '@/components/ModalForm'
import PermissionGuard from '@/components/PermissionGuard'
import { usePagination } from '@/hooks/usePagination'
import * as operApi from '@/api/technology/oper'
import OperForm from './OperForm'
import type { Oper } from '@/types/common'

export default function OperList() {
  const queryClient = useQueryClient()
  const { pagination, onChange, reset } = usePagination()
  const [filters, setFilters] = useState<Record<string, unknown>>({})
  const [modalOpen, setModalOpen] = useState(false)
  const [editId, setEditId] = useState<string | null>(null)
  const [selectedRecord, setSelectedRecord] = useState<Oper | null>(null)
  const [formInstance] = Form.useForm()

  const { data, isLoading } = useQuery({
    queryKey: ['opers', pagination, filters],
    queryFn: () =>
      operApi.page({
        current: pagination.current,
        size: pagination.pageSize,
        ...filters,
      }),
  })

  const saveMutation = useMutation({
    mutationFn: (values: Record<string, unknown>) => operApi.addOrUpdate(values),
    onSuccess: () => {
      message.success('操作成功')
      setModalOpen(false)
      setEditId(null)
      setSelectedRecord(null)
      formInstance.resetFields()
      queryClient.invalidateQueries({ queryKey: ['opers'] })
    },
  })

  const deleteMutation = useMutation({
    mutationFn: (id: string) => operApi.deleteById(id),
    onSuccess: () => {
      message.success('删除成功')
      queryClient.invalidateQueries({ queryKey: ['opers'] })
    },
  })

  const handleSearch = (values: Record<string, unknown>) => {
    setFilters(values)
    reset()
  }

  const handleReset = () => {
    setFilters({})
    reset()
  }

  const handleAdd = () => {
    setEditId(null)
    setSelectedRecord(null)
    formInstance.resetFields()
    setModalOpen(true)
  }

  const handleEdit = (record: Oper) => {
    setEditId(record.id)
    setSelectedRecord(record)
    setModalOpen(true)
  }

  const handleDelete = (record: Oper) => {
    deleteMutation.mutate(record.id)
  }

  const handleModalCancel = () => {
    setModalOpen(false)
    setEditId(null)
    setSelectedRecord(null)
    formInstance.resetFields()
  }

  const handleFormFinish = (values: Record<string, unknown>) => {
    saveMutation.mutate({
      ...values,
      id: editId || undefined,
    })
  }

  const columns = [
    {
      title: '工序编号',
      dataIndex: 'operCode',
      key: 'operCode',
      render: (val: string) => val || '-',
    },
    {
      title: '工序描述',
      dataIndex: 'operDesc',
      key: 'operDesc',
    },
    {
      title: '工时（分钟）',
      dataIndex: 'laborHours',
      key: 'laborHours',
    },
    {
      title: '制造周期（分钟）',
      dataIndex: 'manufacturingCycle',
      key: 'manufacturingCycle',
    },
    {
      title: '生成计划',
      dataIndex: 'generatePlan',
      key: 'generatePlan',
      render: (val: string) =>
        val === '1' ? (
          <Tag color="green">是</Tag>
        ) : (
          <Tag color="default">否</Tag>
        ),
    },
    {
      title: '备注',
      dataIndex: 'remark',
      key: 'remark',
      ellipsis: true,
    },
    {
      title: '操作',
      key: 'action',
      render: (_: unknown, record: Oper) => (
        <span>
          <Button type="link" size="small" onClick={() => handleEdit(record)}>
            编辑
          </Button>
          <Popconfirm title="确定要删除该工序吗？" onConfirm={() => handleDelete(record)}>
            <Button type="link" size="small" danger>
              删除
            </Button>
          </Popconfirm>
        </span>
      ),
    },
  ]

  return (
    <PageContainer>
      <SearchForm onSearch={handleSearch} onReset={handleReset} loading={isLoading}>
        <Form.Item name="operDescLike">
          <Input placeholder="工序描述" />
        </Form.Item>
      </SearchForm>

      <PageTable
        rowKey="id"
        columns={columns}
        dataSource={ensureArray(data?.records)}
        loading={isLoading}
        total={data?.total || 0}
        pagination={{
          current: pagination.current,
          pageSize: pagination.pageSize,
        }}
        onChange={onChange}
        toolbar={
          <PermissionGuard perm="oper:list">
            <Button type="primary" icon={<PlusOutlined />} onClick={handleAdd}>
              新增
            </Button>
          </PermissionGuard>
        }
      />

      <ModalForm
        open={modalOpen}
        title={editId ? '编辑工序' : '新增工序'}
        formInstance={formInstance}
        onCancel={handleModalCancel}
        loading={saveMutation.isPending}
      >
        <OperForm
          id={editId}
          record={selectedRecord}
          formInstance={formInstance}
          onFinish={handleFormFinish}
        />
      </ModalForm>
    </PageContainer>
  )
}
