// mes/frontend/apps/mes-new/src/pages/technology/product-bom/BomItemForm.tsx
import { useEffect } from 'react'
import { Controller, useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import {
  Input,
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
  toast,
} from '@workspace/ui'
import { Package } from 'lucide-react'
import FormDialog, { FormSection } from '@/components/FormDialog'
import FormField from '@/components/FormField'
import { useQuery$, useMutation$ } from '@/http/hooks'
import { productBomItemSave } from '@/api/technology/product-bom'
import { materilePage } from '@/api/basedata/materile'
import { materielToItem } from '@/utils/productBom'
import type { SpProductBomItem } from '@/types/technology'

const ITEM_TYPES = [
  { value: 'material', label: '物料' },
  { value: 'bom_ref', label: '子 BOM 引用' },
]

const UNITS = ['个', '条', '台', '套', 'kg', 'm']

const schema = z.object({
  itemType: z.enum(['material', 'bom_ref']),
  materialCode: z.string().min(1, '请选择物料'),
  materialDesc: z.string().optional(),
  quantity: z.coerce.number({ invalid_type_error: '请输入数量' }).min(0.01, '数量至少 0.01'),
  unit: z.string().optional(),
  sortOrder: z.coerce.number().optional(),
})

type FormValues = z.infer<typeof schema>

const DEFAULTS: FormValues = {
  itemType: 'material',
  materialCode: '',
  materialDesc: '',
  quantity: 1,
  unit: '个',
  sortOrder: 0,
}

interface BomItemFormProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  bomId: string
  initial?: SpProductBomItem
  onSaved: () => void
}

export default function BomItemForm({
  open,
  onOpenChange,
  bomId,
  initial,
  onSaved,
}: BomItemFormProps) {
  const isEdit = !!initial
  const { data: materialsData } = useQuery$(
    ['materile', 'all'],
    () => materilePage({ current: 1, size: 500 }),
    { enabled: open },
  )
  const { mutate, loading } = useMutation$((b: Partial<SpProductBomItem>) => productBomItemSave(b))

  const {
    register,
    handleSubmit,
    control,
    reset,
    setValue,
    formState: { errors },
  } = useForm<FormValues>({
    resolver: zodResolver(schema),
    defaultValues: DEFAULTS,
  })

  useEffect(() => {
    if (open) {
      reset(
        initial
          ? {
              itemType: initial.itemType ?? 'material',
              materialCode: initial.materialCode ?? '',
              materialDesc: initial.materialDesc ?? '',
              quantity: initial.quantity ?? 1,
              unit: initial.unit ?? '个',
              sortOrder: initial.sortOrder ?? 0,
            }
          : DEFAULTS,
      )
    }
  }, [open, initial, reset])

  const onSubmit = handleSubmit(async (values) => {
    try {
      await mutate({
        id: initial?.id,
        bomId,
        itemType: values.itemType,
        materialCode: values.materialCode,
        materialDesc: values.materialDesc ?? '',
        quantity: values.quantity,
        unit: values.unit ?? '个',
        sortOrder: values.sortOrder ?? 0,
      })
      toast.success('已保存物料行')
      onSaved()
      onOpenChange(false)
    } catch {
      /* toast by interceptor */
    }
  })

  return (
    <FormDialog
      open={open}
      onOpenChange={onOpenChange}
      title={isEdit ? '编辑物料行' : '新增物料行'}
      description="维护 BOM 节点下的物料行(物料、数量、单位)"
      icon={Package}
      onSubmit={onSubmit}
      submitting={loading}
    >
      <FormSection title="物料信息" tag="必填">
        <div className="grid grid-cols-2 gap-4">
          <FormField label="行类型" required>
            <Controller
              control={control}
              name="itemType"
              render={({ field }) => (
                <Select value={field.value} onValueChange={field.onChange}>
                  <SelectTrigger className="w-full"><SelectValue /></SelectTrigger>
                  <SelectContent>
                    {ITEM_TYPES.map((t) => (
                      <SelectItem key={t.value} value={t.value}>{t.label}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              )}
            />
          </FormField>
          <FormField label="物料" required error={errors.materialCode?.message}>
            <Controller
              control={control}
              name="materialCode"
              render={({ field }) => (
                <Select
                  value={field.value || undefined}
                  onValueChange={(v) => {
                    field.onChange(v)
                    const m = (materialsData?.records ?? []).find((x) => x.materiel === v)
                    if (m) {
                      const mapped = materielToItem(m)
                      setValue('materialDesc', mapped.materialDesc ?? '')
                      setValue('unit', mapped.unit ?? '个')
                    }
                  }}
                >
                  <SelectTrigger className="w-full"><SelectValue placeholder="请选择物料" /></SelectTrigger>
                  <SelectContent>
                    {(materialsData?.records ?? []).map((m) => (
                      <SelectItem key={m.materiel} value={m.materiel}>{m.materiel} {m.materielDesc}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              )}
            />
          </FormField>
        </div>
        <FormField label="物料描述" htmlFor="item-desc" help="随物料带出,可手动调整">
          <Input id="item-desc" {...register('materialDesc')} />
        </FormField>
        <div className="grid grid-cols-3 gap-4">
          <FormField label="数量" htmlFor="item-qty" required error={errors.quantity?.message}>
            <Input id="item-qty" type="number" step="0.01" aria-invalid={!!errors.quantity} {...register('quantity')} />
          </FormField>
          <FormField label="单位">
            <Controller
              control={control}
              name="unit"
              render={({ field }) => (
                <Select value={field.value || undefined} onValueChange={field.onChange}>
                  <SelectTrigger className="w-full"><SelectValue placeholder="单位" /></SelectTrigger>
                  <SelectContent>
                    {UNITS.map((u) => <SelectItem key={u} value={u}>{u}</SelectItem>)}
                  </SelectContent>
                </Select>
              )}
            />
          </FormField>
          <FormField label="排序" htmlFor="item-sort">
            <Input id="item-sort" type="number" {...register('sortOrder')} />
          </FormField>
        </div>
      </FormSection>
    </FormDialog>
  )
}

// mes/vue3/src/views/technology/product-bom/BomItemForm.vue
<template>
  <FormDialog
    :model-value="modelValue"
    :title="isEdit ? '编辑物料行' : '新增物料行'"
    width="560px"
    :loading="loading"
    @update:model-value="(v) => emit('update:modelValue', v)"
    @submit="handleSubmit"
  >
    <el-form :model="form" label-width="92px">
      <el-form-item label="物料" prop="materialCode">
        <el-select
          v-model="form.materialCode"
          filterable
          placeholder="请选择物料"
          style="width: 100%"
          @change="handlePickMaterial"
        >
          <el-option
            v-for="m in (materials ?? [])"
            :key="m.id"
            :label="`${m.materiel ?? ''} ${m.materielDesc}`"
            :value="m.materiel ?? ''"
          />
        </el-select>
      </el-form-item>

      <el-form-item label="物料描述">
        <el-input v-model="form.materialDesc" placeholder="选择物料后自动带出" />
      </el-form-item>

      <el-row :gutter="16">
        <el-col :span="12">
          <el-form-item label="用量" prop="quantity">
            <el-input-number v-model="form.quantity" :min="0.01" :precision="2" :step="1" controls-position="right" style="width: 100%" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="单位">
            <el-input v-model="form.unit" placeholder="个" />
          </el-form-item>
        </el-col>
      </el-row>

      <el-form-item label="排序">
        <el-input-number v-model="form.sortOrder" :min="0" :precision="0" controls-position="right" style="width: 100%" />
      </el-form-item>
    </el-form>
  </FormDialog>
</template>

<script setup lang="ts">
import { reactive, computed, watch } from 'vue'
import { ElMessage } from 'element-plus'
import FormDialog from '@/components/FormDialog.vue'
import { useRequest } from '@/composables/useRequest'
import { materilePage } from '@/api/basedata/materile'
import { buildBomItemPayload, validateBomItem, materielToItem } from '@/utils/productBom'
import type { SpProductBomItem } from '@/types/technology'
import type { SpMaterile } from '@/types/basedata'

const props = defineProps<{
  modelValue: boolean
  /** 所属节点 id */
  bomId: string
  /** null=新增;有 id=编辑 */
  model: Partial<SpProductBomItem> | null
  loading?: boolean
}>()

const emit = defineEmits<{
  'update:modelValue': [boolean]
  submit: [Partial<SpProductBomItem>]
}>()

const isEdit = computed(() => !!props.model?.id)

// 全量物料下拉(组件行可选任意物料)
const { data: materialsPage } = useRequest(
  () => materilePage({ current: 1, size: 9999 }),
  { immediate: true },
)
const materials = computed<SpMaterile[]>(() => materialsPage.value?.records ?? [])

const form = reactive<Partial<SpProductBomItem>>({
  id: undefined,
  itemType: 'material',
  materialCode: '',
  materialDesc: '',
  quantity: 1,
  unit: '个',
  sortOrder: 0,
})

function resetForm() {
  form.id = undefined
  form.itemType = 'material'
  form.materialCode = ''
  form.materialDesc = ''
  form.quantity = 1
  form.unit = '个'
  form.sortOrder = 0
}

watch(
  () => props.model,
  (val) => {
    if (val) Object.assign(form, { itemType: 'material', quantity: 1, unit: '个', sortOrder: 0, ...val })
    else resetForm()
  },
  { immediate: true },
)

/** 选物料 → 自动带出描述/单位 */
function handlePickMaterial(code: string) {
  const m = materials.value.find((x) => x.materiel === code)
  if (m) {
    const mapped = materielToItem(m)
    form.materialDesc = mapped.materialDesc
    form.unit = mapped.unit
  }
}

function handleSubmit() {
  const err = validateBomItem({ ...form })
  if (err) {
    ElMessage.warning(err)
    return
  }
  emit('submit', buildBomItemPayload({ ...form, bomId: props.bomId }))
}
</script>
