// mes/vue3/src/views/basedata/materile/MaterileForm.vue
<template>
  <FormDialog
    :model-value="modelValue"
    :title="isEdit ? '编辑物料' : '新增物料'"
    width="640px"
    :loading="loading"
    @update:model-value="(v) => emit('update:modelValue', v)"
    @submit="handleSubmit"
  >
    <el-form ref="formRef" :model="form" :rules="rules" label-width="92px">
      <el-row :gutter="16">
        <el-col :span="12">
          <el-form-item label="物料类型" prop="matType">
            <el-select v-model="form.matType" placeholder="请选择物料类型" clearable style="width: 100%">
              <el-option v-for="o in matTypeOptions" :key="o.value" :label="o.label" :value="o.value" />
            </el-select>
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item v-if="isEdit" label="物料编码">
            <el-input :model-value="form.materiel" disabled placeholder="保存后自动生成" />
          </el-form-item>
        </el-col>
      </el-row>

      <el-form-item label="物料描述" prop="materielDesc">
        <el-input v-model="form.materielDesc" placeholder="请输入物料描述" clearable />
      </el-form-item>

      <el-row :gutter="16">
        <el-col :span="12">
          <el-form-item label="基本单位" prop="unit">
            <el-select v-model="form.unit" placeholder="请选择单位" clearable style="width: 100%">
              <el-option v-for="o in unitOptions" :key="o.value" :label="o.label" :value="o.value" />
            </el-select>
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="型号" prop="model">
            <el-input v-model="form.model" placeholder="请输入型号" clearable />
          </el-form-item>
        </el-col>
      </el-row>

      <el-row :gutter="16">
        <el-col :span="12">
          <el-form-item label="物料来源" prop="source">
            <el-select v-model="form.source" placeholder="请选择来源" clearable style="width: 100%">
              <el-option label="自制" value="自制" />
              <el-option label="外购" value="外购" />
            </el-select>
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="规格" prop="size">
            <el-input v-model="form.size" placeholder="请输入规格" clearable />
          </el-form-item>
        </el-col>
      </el-row>

      <el-row :gutter="16">
        <el-col :span="12">
          <el-form-item label="提前期(天)" prop="leadTime">
            <el-input-number v-model="form.leadTime" :min="1" controls-position="right" style="width: 100%" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="安全库存" prop="safetyStock">
            <el-input-number v-model="form.safetyStock" :min="0" controls-position="right" style="width: 100%" />
          </el-form-item>
        </el-col>
      </el-row>

      <el-form-item label="产品组" prop="productGroup">
        <el-input v-model="form.productGroup" placeholder="请输入产品组" clearable />
      </el-form-item>

      <el-form-item label="物料图片">
        <ImageUpload v-model="form.imageUrl" />
      </el-form-item>
    </el-form>
  </FormDialog>
</template>

<script setup lang="ts">
import { ref, reactive, computed, watch } from 'vue'
import type { FormInstance, FormRules } from 'element-plus'
import FormDialog from '@/components/FormDialog.vue'
import ImageUpload from '@/components/ImageUpload.vue'
import { useDict } from '@/composables/useDict'
import { buildMaterilePayload } from '@/utils/materile'
import type { SpMaterile } from '@/types/basedata'

const props = defineProps<{
  modelValue: boolean
  /** null = 新增;Partial(有 id) = 编辑 */
  model: Partial<SpMaterile> | null
  loading?: boolean
}>()

const emit = defineEmits<{
  'update:modelValue': [boolean]
  submit: [Partial<SpMaterile>]
}>()

const formRef = ref<FormInstance>()
const isEdit = computed(() => !!props.model?.id)

// 动态字典下拉(模块级缓存,列表页与表单共享同一请求)
const { options: matTypeOptions } = useDict('material_type')
const { options: unitOptions } = useDict('ORDER_UNIT')

const form = reactive<Partial<SpMaterile>>({
  id: undefined,
  materiel: undefined,
  materielDesc: '',
  unit: undefined,
  matType: undefined,
  model: undefined,
  source: undefined,
  size: undefined,
  leadTime: 1,
  safetyStock: 0,
  productGroup: undefined,
  imageUrl: '',
})

function resetForm() {
  form.id = undefined
  form.materiel = undefined
  form.materielDesc = ''
  form.unit = undefined
  form.matType = undefined
  form.model = undefined
  form.source = undefined
  form.size = undefined
  form.leadTime = 1
  form.safetyStock = 0
  form.productGroup = undefined
  form.imageUrl = ''
}

watch(
  () => props.model,
  (val) => {
    if (val) Object.assign(form, { leadTime: 1, safetyStock: 0, imageUrl: '', ...val })
    else resetForm()
  },
  { immediate: true },
)

const rules: FormRules = {
  matType: [{ required: true, message: '请选择物料类型', trigger: 'change' }],
  materielDesc: [{ required: true, message: '请输入物料描述', trigger: 'blur' }],
}

async function handleSubmit() {
  await formRef.value?.validate()
  emit('submit', buildMaterilePayload({ ...form }))
}
</script>

// mes/frontend/apps/mes-new/src/pages/basedata/materile/MaterileForm.tsx
// apps/mes-new/src/pages/basedata/materile/MaterileForm.tsx
import { useEffect } from 'react'
import { Controller, useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import {
  Input,
  Label,
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
  toast,
} from '@workspace/ui'
import ModalForm from '@/components/ModalForm'
import ImageUpload from '@/components/ImageUpload'
import { useMutation$ } from '@/http/hooks'
import { invalidate } from '@/http/queryCache'
import { materileAddOrUpdate } from '@/api/basedata/materile'
import type { Materiel } from '@/types/basedata'

interface MaterileFormProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  record?: Materiel | null
  onSaved: () => void
}

const MAT_TYPES = ['产品', '零件', '标准件', '其他'] as const
const SOURCES = ['自制', '外购'] as const
const TYPE_DEFAULTS: Record<string, { source: string; leadTime: number }> = {
  产品: { source: '自制', leadTime: 3 },
  零件: { source: '外购', leadTime: 1 },
  标准件: { source: '外购', leadTime: 1 },
  其他: { source: '外购', leadTime: 1 },
}

const schema = z.object({
  matType: z.string().min(1, '请选择物料类型'),
  materielDesc: z.string().min(1, '请输入物料描述'),
  model: z.string().optional(),
  unit: z.string().optional(),
  source: z.string().optional(),
  size: z.string().optional(),
  productGroup: z.string().optional(),
  leadTime: z.coerce.number().int().min(1, '提前期最小为 1'),
  safetyStock: z.coerce.number().int().min(0, '安全库存不能为负'),
  imageUrl: z.string().optional(),
})

export default function MaterileForm({ open, onOpenChange, record, onSaved }: MaterileFormProps) {
  const isEdit = !!record
  const { mutate, loading } = useMutation$((dto: Partial<Materiel>) => materileAddOrUpdate(dto))
  const {
    register,
    handleSubmit,
    control,
    setValue,
    reset,
    formState: { errors },
  } = useForm<z.infer<typeof schema>>({
    resolver: zodResolver(schema),
    defaultValues: { matType: '', materielDesc: '', model: '', unit: '', source: '', size: '', productGroup: '', leadTime: 1, safetyStock: 0, imageUrl: '' },
  })

  useEffect(() => {
    if (open) {
      reset({
        matType: record?.matType ?? '',
        materielDesc: record?.materielDesc ?? '',
        model: record?.model ?? '',
        unit: record?.unit ?? '',
        source: record?.source ?? '',
        size: record?.size ?? '',
        productGroup: record?.productGroup ?? '',
        leadTime: record?.leadTime ?? 1,
        safetyStock: record?.safetyStock ?? 0,
        imageUrl: record?.imageUrl ?? '',
      })
    }
  }, [open, record, reset])

  const onSubmit = handleSubmit(async (values) => {
    const dto: Partial<Materiel> = {
      ...(record ?? { deleted: '0' }),
      matType: values.matType,
      materielDesc: values.materielDesc,
      model: values.model ?? '',
      unit: values.unit ?? '',
      source: values.source ?? '',
      size: values.size ?? '',
      productGroup: values.productGroup ?? '',
      leadTime: values.leadTime,
      safetyStock: values.safetyStock,
      imageUrl: values.imageUrl ?? '',
    }
    try {
      await mutate(dto)
      toast.success(isEdit ? '修改成功' : '新增成功')
      invalidate('["basedata","materile"')
      onOpenChange(false)
      onSaved()
    } catch {
      /* 拦截器已 toast */
    }
  })

  return (
    <ModalForm open={open} onOpenChange={onOpenChange} title={isEdit ? '编辑物料' : '新增物料'} onSubmit={onSubmit} submitting={loading}>
      <div className="grid grid-cols-2 gap-3">
        <div className="space-y-1.5">
          <Label>物料类型</Label>
          <Controller
            control={control}
            name="matType"
            render={({ field }) => (
              <Select
                value={field.value}
                onValueChange={(v) => {
                  field.onChange(v)
                  const d = TYPE_DEFAULTS[v]
                  if (d) {
                    setValue('source', d.source)
                    setValue('leadTime', d.leadTime)
                  }
                }}
              >
                <SelectTrigger className="w-full"><SelectValue placeholder="请选择类型" /></SelectTrigger>
                <SelectContent>
                  {MAT_TYPES.map((t) => <SelectItem key={t} value={t}>{t}</SelectItem>)}
                </SelectContent>
              </Select>
            )}
          />
          {errors.matType && <p className="text-xs text-destructive">{errors.matType.message}</p>}
        </div>
        {isEdit && (
          <div className="space-y-1.5">
            <Label htmlFor="m-materiel">物料编码</Label>
            <Input id="m-materiel" value={record?.materiel ?? ''} disabled />
          </div>
        )}
      </div>
      <div className="space-y-1.5">
        <Label htmlFor="m-desc">物料描述</Label>
        <Input id="m-desc" {...register('materielDesc')} />
        {errors.materielDesc && <p className="text-xs text-destructive">{errors.materielDesc.message}</p>}
      </div>
      <div className="grid grid-cols-2 gap-3">
        <div className="space-y-1.5">
          <Label htmlFor="m-model">型号</Label>
          <Input id="m-model" {...register('model')} />
        </div>
        <div className="space-y-1.5">
          <Label htmlFor="m-unit">单位</Label>
          <Input id="m-unit" {...register('unit')} />
        </div>
      </div>
      <div className="grid grid-cols-2 gap-3">
        <div className="space-y-1.5">
          <Label>物料来源</Label>
          <Controller
            control={control}
            name="source"
            render={({ field }) => (
              <Select value={field.value || undefined} onValueChange={field.onChange}>
                <SelectTrigger className="w-full"><SelectValue placeholder="请选择来源" /></SelectTrigger>
                <SelectContent>
                  {SOURCES.map((s) => <SelectItem key={s} value={s}>{s}</SelectItem>)}
                </SelectContent>
              </Select>
            )}
          />
        </div>
        <div className="space-y-1.5">
          <Label htmlFor="m-size">规格</Label>
          <Input id="m-size" {...register('size')} />
        </div>
      </div>
      <div className="grid grid-cols-2 gap-3">
        <div className="space-y-1.5">
          <Label htmlFor="m-lead">提前期(天)</Label>
          <Input id="m-lead" type="number" {...register('leadTime')} />
          {errors.leadTime && <p className="text-xs text-destructive">{errors.leadTime.message}</p>}
        </div>
        <div className="space-y-1.5">
          <Label htmlFor="m-stock">安全库存</Label>
          <Input id="m-stock" type="number" {...register('safetyStock')} />
          {errors.safetyStock && <p className="text-xs text-destructive">{errors.safetyStock.message}</p>}
        </div>
      </div>
      <div className="space-y-1.5">
        <Label htmlFor="m-group">产品组</Label>
        <Input id="m-group" {...register('productGroup')} />
      </div>
      <div className="space-y-1.5">
        <Label>物料图片</Label>
        <Controller
          control={control}
          name="imageUrl"
          render={({ field }) => <ImageUpload value={field.value} onChange={field.onChange} />}
        />
      </div>
    </ModalForm>
  )
}
