// mes/vue3/src/views/technology/flow/FlowList.vue
<template>
  <PageContainer>
    <DataTable
      :data="tableData"
      :loading="loading"
      :columns="columns"
      :pager="pager"
      @page-change="handlePageChange"
      @size-change="handleSizeChange"
    >
      <template #toolbar>
        <el-button v-permission="'flow:add'" type="primary" :icon="Plus" @click="openCreate">新建工艺路线</el-button>
      </template>

      <template #col-process="{ row }">
        <span v-if="row.process" class="flow-chain">
          <template v-for="(seg, i) in row.process.split('->')" :key="i">
            <el-tag size="small" disable-transitions>{{ seg }}</el-tag>
            <el-icon v-if="(i as number) < row.process.split('->').length - 1" class="flow-chain__arrow"><Right /></el-icon>
          </template>
        </span>
        <el-tag v-else size="small" type="info">未编排</el-tag>
      </template>

      <template #actions="{ row }">
        <el-button type="primary" link size="small" @click="openEdit(row as SpFlow)">编辑</el-button>
        <el-button type="danger" link size="small" @click="handleDelete(row as SpFlow)">删除</el-button>
      </template>
    </DataTable>

    <FlowProcessEditor
      v-model="dialogVisible"
      :model="editingModel"
      :loading="submitLoading"
      @submit="handleFormSubmit"
    />
  </PageContainer>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Plus, Right } from '@element-plus/icons-vue'
import PageContainer from '@/components/PageContainer.vue'
import DataTable, { type Column } from '@/components/DataTable.vue'
import FlowProcessEditor from './FlowProcessEditor.vue'
import { useRequest } from '@/composables/useRequest'
import { usePagination } from '@/composables/usePagination'
import { flowPage, flowSaveProcess, flowDelete } from '@/api/technology/flow'
import type { SpFlow, SpFlowDtoReq } from '@/types/technology'

const { pager, setTotal, reset } = usePagination()

const { data: pageData, loading, run } = useRequest(
  () => flowPage({ current: pager.current, size: pager.size }),
  { immediate: true },
)

const tableData = computed<SpFlow[]>(() => {
  const result = pageData.value
  if (result) setTotal(result.total)
  return result?.records ?? []
})

const columns: Column[] = [
  { prop: 'flow', label: '流程代码', width: 140 },
  { prop: 'flowDesc', label: '流程描述', width: 160 },
  { prop: 'process', label: '工序链', minWidth: 320 },
  { prop: 'createTime', label: '创建时间', minWidth: 160 },
]

const dialogVisible = ref(false)
const editingModel = ref<SpFlow | null>(null)
const submitLoading = ref(false)

function openCreate() {
  editingModel.value = null
  dialogVisible.value = true
}
function openEdit(row: SpFlow) {
  editingModel.value = { ...row }
  dialogVisible.value = true
}

function handlePageChange(page: number) {
  pager.current = page
  run()
}
function handleSizeChange(size: number) {
  pager.size = size
  reset()
  run()
}

async function handleFormSubmit(dto: SpFlowDtoReq) {
  submitLoading.value = true
  try {
    await flowSaveProcess(dto)
    ElMessage.success('保存成功')
    dialogVisible.value = false
    run()
  } finally {
    submitLoading.value = false
  }
}

async function handleDelete(row: SpFlow) {
  try {
    await ElMessageBox.confirm(`确认删除工艺路线「${row.flow}」?将同时删除其工序编排。`, '提示', {
      type: 'warning',
      confirmButtonText: '确认删除',
      cancelButtonText: '取消',
    })
  } catch {
    return
  }
  try {
    await flowDelete(row.id)
    ElMessage.success('删除成功')
    run()
  } catch { /* 响应拦截器已提示 */ }
}
</script>

<style scoped>
.flow-chain { display: inline-flex; align-items: center; flex-wrap: wrap; gap: 4px; }
.flow-chain__arrow { color: var(--el-text-color-secondary); }
</style>

// mes/frontend/apps/mes-new/src/pages/technology/flow/FlowList.tsx
import { useMemo, useState } from 'react'
import type { ColumnDef } from '@tanstack/react-table'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  Badge,
  Button,
  DataTable,
  toast,
} from '@workspace/ui'
import { ArrowRight, Pencil, Plus, Trash2 } from 'lucide-react'
import PageContainer from '@/components/PageContainer'
import PermissionGuard from '@/components/PermissionGuard'
import FlowProcessEditor from './FlowProcessEditor'
import { useQuery$, useMutation$ } from '@/http/hooks'
import { invalidate } from '@/http/queryCache'
import { flowPage, flowDelete } from '@/api/technology/flow'
import type { PageParams } from '@/types/api'
import type { SpFlow } from '@/types/technology'

const PAGE_SIZE = 10

export default function FlowList() {
  const [params, setParams] = useState<PageParams>({ current: 1, size: PAGE_SIZE })
  const [formOpen, setFormOpen] = useState(false)
  const [editing, setEditing] = useState<SpFlow | null>(null)
  const [deleting, setDeleting] = useState<SpFlow | null>(null)

  const { data, loading } = useQuery$(['flow', 'page', params], () => flowPage(params))
  const { mutate: removeFlow } = useMutation$((id: string) => flowDelete(id))

  const confirmDelete = async () => {
    if (!deleting) return
    try {
      await removeFlow(deleting.id)
      toast.success('删除成功')
      invalidate('["flow","page"')
    } catch {
      /* toast */
    } finally {
      setDeleting(null)
    }
  }

  const columns = useMemo<ColumnDef<SpFlow>[]>(
    () => [
      { accessorKey: 'flow', header: '流程代码' },
      { accessorKey: 'flowDesc', header: '流程描述', cell: ({ row }) => row.original.flowDesc || '—' },
      {
        accessorKey: 'process',
        header: '工序链',
        cell: ({ row }) => {
          const p = row.original.process
          if (!p) return <span className="text-muted-foreground">—</span>
          const parts = p.split('->')
          return (
            <div className="flex flex-wrap items-center gap-1">
              {parts.map((s, i) => (
                <span key={i} className="flex items-center gap-1">
                  <Badge variant="secondary" className="font-normal">{s}</Badge>
                  {i < parts.length - 1 && <ArrowRight className="size-3 text-muted-foreground" />}
                </span>
              ))}
            </div>
          )
        },
      },
      {
        id: 'actions',
        header: '操作',
        cell: ({ row }) => (
          <div className="flex gap-1">
            <Button variant="ghost" size="icon-sm" onClick={() => { setEditing(row.original); setFormOpen(true) }}>
              <Pencil className="size-4" />
            </Button>
            <Button variant="ghost" size="icon-sm" onClick={() => setDeleting(row.original)}>
              <Trash2 className="size-4 text-destructive" />
            </Button>
          </div>
        ),
      },
    ],
    [],
  )

  return (
    <PageContainer
      title="工艺路线管理"
      description="编排工序生成工艺路线"
      actions={
        <PermissionGuard perm="flow:add">
          <Button onClick={() => { setEditing(null); setFormOpen(true) }}>
            <Plus className="size-4" />
            新建工艺路线
          </Button>
        </PermissionGuard>
      }
    >
      <DataTable
        columns={columns}
        data={data?.records ?? []}
        loading={loading}
        loadingRowCount={PAGE_SIZE}
        pagination={{
          mode: 'server',
          pageIndex: (data?.current ?? params.current) - 1,
          pageSize: PAGE_SIZE,
          totalPages: data?.pages ?? 1,
          totalRows: data?.total,
          onPageChange: (idx) => setParams((p) => ({ ...p, current: idx + 1 })),
        }}
      />

      <FlowProcessEditor open={formOpen} onOpenChange={setFormOpen} record={editing} />

      <AlertDialog open={!!deleting} onOpenChange={(o) => !o && setDeleting(null)}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>确认删除</AlertDialogTitle>
            <AlertDialogDescription>确定删除工艺路线「{deleting?.flow}」吗?将同时删除其工序关系。</AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>取消</AlertDialogCancel>
            <AlertDialogAction onClick={confirmDelete}>删除</AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </PageContainer>
  )
}
