// mes/frontend/apps/mes-new/src/pages/workflow/definition/EventConfigDialog.tsx
import { useEffect, useState } from 'react'
import {
  Badge,
  Button,
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  Input,
  Label,
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
  Switch,
  toast,
} from '@workspace/ui'
import { Plus, Trash2, Wand2 } from 'lucide-react'
import { firstValueFrom } from 'rxjs'
import ScriptEditor from '@/components/ScriptEditor'
import { eventList, eventSave, eventDelete } from '@/api/workflow/event'
import {
  TRIGGER_OPTIONS,
  ACTION_OPTIONS,
  AUDIT_STATUS_OPTIONS,
  triggerLabel,
  auditStatusLabel,
  defaultEventRules,
} from '@/pages/workflow/formUtils'
import type {
  OrderAuditStatus,
  WorkflowDefinition,
  WorkflowEventActionType,
  WorkflowEventRule,
  WorkflowEventTrigger,
} from '@/types/workflow'

interface EventConfigDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  definition: WorkflowDefinition | null
}

interface Draft {
  id: string
  name: string
  trigger: WorkflowEventTrigger
  actionType: WorkflowEventActionType
  targetStatus: OrderAuditStatus
  script: string
  enabled: boolean
}

const EMPTY_DRAFT: Draft = {
  id: '',
  name: '',
  trigger: 'START',
  actionType: 'SET_AUDIT_STATUS',
  targetStatus: 'APPROVING',
  script: '',
  enabled: true,
}

export default function EventConfigDialog({ open, onOpenChange, definition }: EventConfigDialogProps) {
  const [rules, setRules] = useState<WorkflowEventRule[]>([])
  const [draft, setDraft] = useState<Draft>(EMPTY_DRAFT)

  const reload = async () => {
    if (!definition) return
    setRules(await firstValueFrom(eventList(definition.id)))
  }

  useEffect(() => {
    if (open && definition) {
      setDraft(EMPTY_DRAFT)
      void reload()
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, definition])

  const persist = async (rule: WorkflowEventRule) => {
    await firstValueFrom(eventSave(rule))
    await reload()
  }

  const onAddOrUpdate = async () => {
    if (!definition) return
    if (draft.actionType === 'SCRIPT' && !draft.script.trim()) {
      toast.error('请填写脚本内容')
      return
    }
    const rule: WorkflowEventRule = {
      id: draft.id,
      definitionId: definition.id,
      name: draft.name || undefined,
      trigger: draft.trigger,
      businessType: 'ORDER_APPROVAL',
      actionType: draft.actionType,
      targetStatus: draft.actionType === 'SET_AUDIT_STATUS' ? draft.targetStatus : undefined,
      script: draft.actionType === 'SCRIPT' ? draft.script : undefined,
      enabled: draft.enabled,
    }
    await persist(rule)
    setDraft(EMPTY_DRAFT)
    toast.success(draft.id ? '规则已更新' : '规则已添加')
  }

  const onEdit = (r: WorkflowEventRule) => {
    setDraft({
      id: r.id,
      name: r.name ?? '',
      trigger: r.trigger,
      actionType: r.actionType,
      targetStatus: r.targetStatus ?? 'APPROVING',
      script: r.script ?? '',
      enabled: r.enabled,
    })
  }

  const onDelete = async (id: string) => {
    await firstValueFrom(eventDelete(id))
    await reload()
    if (draft.id === id) setDraft(EMPTY_DRAFT)
  }

  const onFillSample = async () => {
    if (!definition) return
    for (const d of defaultEventRules(definition.id)) {
      await firstValueFrom(eventSave({ id: '', ...d }))
    }
    await reload()
    toast.success('已填入生产订单审批示例规则')
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-2xl">
        <DialogHeader>
          <DialogTitle>流程事件配置</DialogTitle>
          <DialogDescription>
            为「{definition?.processName}」配置审批过程/结束时的业务状态同步(生产订单 audit_status)。
          </DialogDescription>
        </DialogHeader>

        {/* 编辑器 */}
        <div className="space-y-3 rounded-md border p-3">
          <div className="grid grid-cols-2 gap-3">
            <div className="space-y-1.5">
              <Label>规则名称</Label>
              <Input value={draft.name} onChange={(e) => setDraft((d) => ({ ...d, name: e.target.value }))} placeholder="可选" />
            </div>
            <div className="space-y-1.5">
              <Label>触发时机</Label>
              <Select value={draft.trigger} onValueChange={(v) => setDraft((d) => ({ ...d, trigger: v as WorkflowEventTrigger }))}>
                <SelectTrigger className="w-full"><SelectValue /></SelectTrigger>
                <SelectContent>
                  {TRIGGER_OPTIONS.map((o) => <SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-1.5">
              <Label>同步动作</Label>
              <Select value={draft.actionType} onValueChange={(v) => setDraft((d) => ({ ...d, actionType: v as WorkflowEventActionType }))}>
                <SelectTrigger className="w-full"><SelectValue /></SelectTrigger>
                <SelectContent>
                  {ACTION_OPTIONS.map((o) => <SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}
                </SelectContent>
              </Select>
            </div>
            {draft.actionType === 'SET_AUDIT_STATUS' ? (
              <div className="space-y-1.5">
                <Label>目标审批状态</Label>
                <Select value={draft.targetStatus} onValueChange={(v) => setDraft((d) => ({ ...d, targetStatus: v as OrderAuditStatus }))}>
                  <SelectTrigger className="w-full"><SelectValue /></SelectTrigger>
                  <SelectContent>
                    {AUDIT_STATUS_OPTIONS.map((o) => <SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}
                  </SelectContent>
                </Select>
              </div>
            ) : (
              <div className="col-span-2 space-y-1.5">
                <Label>脚本</Label>
                <ScriptEditor value={draft.script} onChange={(v) => setDraft((d) => ({ ...d, script: v }))} />
              </div>
            )}
          </div>
          <div className="flex items-center justify-between">
            <label className="flex items-center gap-2 text-sm">
              <Switch checked={draft.enabled} onCheckedChange={(v) => setDraft((d) => ({ ...d, enabled: v }))} />
              <span>启用</span>
            </label>
            <div className="flex gap-2">
              <Button variant="outline" size="sm" onClick={onFillSample}>
                <Wand2 className="size-4" />填入示例
              </Button>
              <Button size="sm" onClick={onAddOrUpdate}>
                <Plus className="size-4" />{draft.id ? '更新规则' : '添加规则'}
              </Button>
            </div>
          </div>
        </div>

        {/* 规则列表 */}
        <div className="space-y-2">
          {rules.length === 0 && <p className="py-4 text-center text-sm text-muted-foreground">暂无事件规则</p>}
          {rules.map((r) => (
            <div key={r.id} className="flex items-center justify-between rounded-md border px-3 py-2 text-sm">
              <div className="flex items-center gap-2">
                <Badge variant="outline">{triggerLabel(r.trigger)}</Badge>
                <span className="text-muted-foreground">→</span>
                <span>
                  {r.actionType === 'SET_AUDIT_STATUS' ? `设置审批状态 = ${auditStatusLabel(r.targetStatus)}` : '执行脚本'}
                </span>
                {!r.enabled && <Badge variant="secondary">已停用</Badge>}
                {r.name && <span className="text-xs text-muted-foreground">({r.name})</span>}
              </div>
              <div className="flex gap-1">
                <Button variant="ghost" size="icon-sm" onClick={() => onEdit(r)}>编辑</Button>
                <Button variant="ghost" size="icon-sm" onClick={() => onDelete(r.id)}>
                  <Trash2 className="size-4 text-destructive" />
                </Button>
              </div>
            </div>
          ))}
        </div>

        <DialogFooter>
          <Button onClick={() => onOpenChange(false)}>完成</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}

// mes/vue3/src/views/workflow/definition/EventConfigDialog.vue
<template>
  <el-dialog
    :model-value="modelValue"
    title="流程事件规则"
    width="760px"
    @update:model-value="(v: boolean) => emit('update:modelValue', v)"
  >
    <div v-if="definition" class="event-cfg">
      <!-- 编辑器 -->
      <el-form :model="draft" label-width="92px" class="event-cfg__editor">
        <el-row :gutter="16">
          <el-col :span="12">
            <el-form-item label="规则名称">
              <el-input v-model="draft.name" placeholder="可选,如:发起即审批中" clearable />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="触发时机">
              <el-select v-model="draft.trigger" style="width: 100%">
                <el-option v-for="o in TRIGGER_OPTIONS" :key="o.value" :label="o.label" :value="o.value" />
              </el-select>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row :gutter="16">
          <el-col :span="12">
            <el-form-item label="动作类型">
              <el-select v-model="draft.actionType" style="width: 100%">
                <el-option v-for="o in ACTION_OPTIONS" :key="o.value" :label="o.label" :value="o.value" />
              </el-select>
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item v-if="draft.actionType === 'SET_AUDIT_STATUS'" label="目标状态">
              <el-select v-model="draft.targetStatus" style="width: 100%" clearable>
                <el-option v-for="o in AUDIT_STATUS_OPTIONS" :key="o.value" :label="o.label" :value="o.value" />
              </el-select>
            </el-form-item>
          </el-col>
        </el-row>
        <el-form-item v-if="draft.actionType === 'SCRIPT'" label="业务脚本">
          <el-input v-model="draft.script" type="textarea" :rows="3" placeholder="请输入业务脚本" />
        </el-form-item>
        <el-form-item label="启用">
          <el-switch v-model="draft.enabled" />
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="handleSaveRule">
            {{ draft.id ? '更新规则' : '添加规则' }}
          </el-button>
          <el-button v-if="draft.id" @click="resetDraft">取消编辑</el-button>
          <el-button text @click="handleFillSample">填入示例</el-button>
        </el-form-item>
      </el-form>

      <!-- 规则列表 -->
      <el-divider content-position="left">已配置规则({{ rules.length }})</el-divider>
      <div v-loading="loading" class="event-cfg__list">
        <el-empty v-if="!rules.length" description="暂无事件规则" :image-size="60" />
        <div v-for="r in rules" v-else :key="r.id" class="event-cfg__item">
          <div class="event-cfg__item-main">
            <el-tag size="small">{{ triggerLabel(r.trigger) }}</el-tag>
            <span class="event-cfg__desc">{{ ruleDesc(r) }}</span>
            <span v-if="r.name" class="event-cfg__name">{{ r.name }}</span>
            <el-tag v-if="!r.enabled" size="small" type="info">已停用</el-tag>
          </div>
          <div class="event-cfg__item-ops">
            <el-button type="primary" link size="small" @click="editRule(r)">编辑</el-button>
            <el-button type="danger" link size="small" @click="handleDeleteRule(r)">删除</el-button>
          </div>
        </div>
      </div>
    </div>
  </el-dialog>
</template>

<script setup lang="ts">
import { ref, reactive, watch } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import {
  TRIGGER_OPTIONS,
  ACTION_OPTIONS,
  AUDIT_STATUS_OPTIONS,
  triggerLabel,
  actionLabel,
  auditStatusLabel,
  validateEventRule,
  buildEventPayload,
  sampleEventRules,
} from '@/utils/workflow'
import { eventList, eventSave, eventDelete } from '@/api/workflow/event'
import type { WorkflowDefinition, WorkflowEventRule } from '@/types/workflow'

const props = defineProps<{
  modelValue: boolean
  definition: WorkflowDefinition | null
}>()

const emit = defineEmits<{ 'update:modelValue': [boolean] }>()

const rules = ref<WorkflowEventRule[]>([])
const loading = ref(false)

function blankDraft(): Partial<WorkflowEventRule> {
  return {
    id: undefined,
    definitionId: props.definition?.id,
    name: '',
    trigger: 'START',
    businessType: 'ORDER_APPROVAL',
    actionType: 'SET_AUDIT_STATUS',
    targetStatus: 'APPROVING',
    script: '',
    enabled: true,
  }
}

const draft = reactive<Partial<WorkflowEventRule>>(blankDraft())

function resetDraft() {
  Object.assign(draft, blankDraft())
}

async function loadRules() {
  if (!props.definition) return
  loading.value = true
  try {
    rules.value = await eventList(props.definition.id)
  } finally {
    loading.value = false
  }
}

watch(
  () => props.modelValue,
  (open) => {
    if (!open) return
    resetDraft()
    loadRules()
  },
)

function ruleDesc(r: WorkflowEventRule): string {
  if (r.actionType === 'SET_AUDIT_STATUS') {
    return `${actionLabel(r.actionType)} → ${auditStatusLabel(r.targetStatus)}`
  }
  return actionLabel(r.actionType)
}

function editRule(r: WorkflowEventRule) {
  Object.assign(draft, blankDraft(), r)
}

async function handleSaveRule() {
  const err = validateEventRule(draft)
  if (err) {
    ElMessage.warning(err)
    return
  }
  await eventSave(buildEventPayload({ ...draft, definitionId: props.definition!.id }))
  ElMessage.success('保存成功')
  resetDraft()
  loadRules()
}

async function handleDeleteRule(r: WorkflowEventRule) {
  try {
    await ElMessageBox.confirm('确认删除该事件规则?', '提示', {
      type: 'warning',
      confirmButtonText: '确认删除',
      cancelButtonText: '取消',
    })
  } catch {
    return
  }
  try {
    await eventDelete(r.id!)
    ElMessage.success('删除成功')
    loadRules()
  } catch { /* 响应拦截器已提示 */ }
}

async function handleFillSample() {
  if (!props.definition) return
  const samples = sampleEventRules(props.definition.id)
  for (const s of samples) {
    await eventSave(buildEventPayload(s))
  }
  ElMessage.success('示例规则已填入')
  loadRules()
}
</script>

<style scoped>
.event-cfg__list {
  min-height: 80px;
}
.event-cfg__item {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 8px 12px;
  border: 1px solid var(--el-border-color-lighter);
  border-radius: 6px;
  margin-bottom: 8px;
}
.event-cfg__item-main {
  display: flex;
  align-items: center;
  gap: 10px;
  min-width: 0;
}
.event-cfg__desc {
  color: var(--el-text-color-primary);
}
.event-cfg__name {
  color: var(--el-text-color-secondary);
  font-size: 12px;
}
</style>
