// mes/vue3/src/views/order/release/OrderList.vue
<template>
  <PageContainer>
    <SearchForm :model="search" @search="handleSearch" @reset="handleReset">
      <el-form-item label="工单编号">
        <el-input v-model="search.orderCodeLike" placeholder="工单编号" clearable />
      </el-form-item>
      <el-form-item label="物料">
        <el-input v-model="search.materielLike" placeholder="物料编码" clearable />
      </el-form-item>
    </SearchForm>

    <DataTable
      :data="tableData"
      :loading="loading"
      :columns="columns"
      :pager="pager"
      @page-change="handlePageChange"
      @size-change="handleSizeChange"
    >
      <template #toolbar>
        <el-button v-permission="'order:add'" type="primary" :icon="Plus" @click="openCreate">新增工单</el-button>
      </template>

      <template #col-orderType="{ row }">
        <el-tag size="small" type="info">{{ orderTypeLabel(row.orderType) }}</el-tag>
      </template>
      <template #col-statue="{ row }">
        <el-tag size="small" :type="orderStatusMeta(row.statue).tag">{{ orderStatusMeta(row.statue).label }}</el-tag>
      </template>

      <template #actions="{ row }">
        <el-button type="primary" link size="small" @click="openEdit(row as SpOrder)">编辑</el-button>
        <el-button type="danger" link size="small" @click="handleDelete(row as SpOrder)">删除</el-button>
      </template>
    </DataTable>

    <OrderForm v-model="dialogVisible" :model="editingModel" :loading="submitLoading" @submit="handleFormSubmit" />
  </PageContainer>
</template>

<script setup lang="ts">
import { ref, reactive, computed } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Plus } from '@element-plus/icons-vue'
import PageContainer from '@/components/PageContainer.vue'
import SearchForm from '@/components/SearchForm.vue'
import DataTable, { type Column } from '@/components/DataTable.vue'
import OrderForm from './OrderForm.vue'
import { useRequest } from '@/composables/useRequest'
import { usePagination } from '@/composables/usePagination'
import { orderPage, orderAddOrUpdate, orderDelete } from '@/api/order/order'
import { orderTypeLabel, orderStatusMeta } from '@/utils/order'
import type { SpOrder } from '@/types/order'

const { pager, setTotal, reset } = usePagination()
const search = reactive({ orderCodeLike: '', materielLike: '' })

const { data: pageData, loading, run } = useRequest(
  () => orderPage({ current: pager.current, size: pager.size, ...search }),
  { immediate: true },
)
const tableData = computed<SpOrder[]>(() => {
  const r = pageData.value
  if (r) setTotal(r.total)
  return r?.records ?? []
})

const columns: Column[] = [
  { prop: 'orderCode', label: '工单编号', width: 150 },
  { prop: 'orderDescription', label: '描述', minWidth: 140 },
  { prop: 'qty', label: '数量', width: 80 },
  { prop: 'orderType', label: '类型', width: 90 },
  { prop: 'materiel', label: '物料', width: 120 },
  { prop: 'planStartTime', label: '计划开始', minWidth: 150 },
  { prop: 'planEndTime', label: '计划结束', minWidth: 150 },
  { prop: 'statue', label: '状态', width: 90 },
]

const dialogVisible = ref(false)
const editingModel = ref<Partial<SpOrder> | null>(null)
const submitLoading = ref(false)

function openCreate() {
  editingModel.value = null
  dialogVisible.value = true
}
function openEdit(row: SpOrder) {
  editingModel.value = { ...row }
  dialogVisible.value = true
}
function handlePageChange(p: number) {
  pager.current = p
  run()
}
function handleSizeChange(s: number) {
  pager.size = s
  reset()
  run()
}
function handleSearch() {
  reset()
  run()
}
function handleReset() {
  search.orderCodeLike = ''
  search.materielLike = ''
  reset()
  run()
}

async function handleFormSubmit(dto: Partial<SpOrder>) {
  submitLoading.value = true
  try {
    await orderAddOrUpdate(dto)
    ElMessage.success('保存成功')
    dialogVisible.value = false
    run()
  } finally {
    submitLoading.value = false
  }
}

async function handleDelete(row: SpOrder) {
  try {
    await ElMessageBox.confirm(`确认删除工单「${row.orderCode}」?`, '提示', {
      type: 'warning',
      confirmButtonText: '确认删除',
      cancelButtonText: '取消',
    })
  } catch {
    return
  }
  try {
    await orderDelete(row.id!)
    ElMessage.success('删除成功')
    run()
  } catch {
    /* 拦截器已提示 */
  }
}
</script>

// mes/frontend/src/pages/order/OrderList.tsx
import { useState } from 'react'
import { Form, Button, Input, Tag, Popconfirm, message } from 'antd'
import { PlusOutlined } from '@ant-design/icons'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import PageContainer from '@/components/PageContainer'
import { ensureArray } from '@/utils/ensureArray'
import SearchForm from '@/components/SearchForm'
import PageTable from '@/components/PageTable'
import ModalForm from '@/components/ModalForm'
import PermissionGuard from '@/components/PermissionGuard'
import { usePagination } from '@/hooks/usePagination'
import * as productionApi from '@/api/order/production'
import OrderForm from './OrderForm'
import type { ProductionOrder } from '@/types/common'

const orderTypeMap: Record<string, { text: string; color: string }> = {
  P: { text: '批量', color: 'blue' },
  A: { text: '验证', color: 'orange' },
  F: { text: '返工', color: 'red' },
}

const statueMap: Record<string, { text: string; color: string }> = {
  '1': { text: '已创建', color: 'default' },
  '2': { text: '进行中', color: 'processing' },
  '3': { text: '已完成', color: 'success' },
  '4': { text: '已终止', color: 'error' },
}

export default function OrderList() {
  const queryClient = useQueryClient()
  const { pagination, onChange, reset } = usePagination()
  const [filters, setFilters] = useState<Record<string, unknown>>({})
  const [modalOpen, setModalOpen] = useState(false)
  const [editId, setEditId] = useState<string | null>(null)
  const [formInstance] = Form.useForm()

  const { data, isLoading } = useQuery({
    queryKey: ['orders', pagination, filters],
    queryFn: () =>
      productionApi.page({
        current: pagination.current,
        size: pagination.pageSize,
        ...filters,
      }),
  })

  const saveMutation = useMutation({
    mutationFn: (values: Record<string, unknown>) => productionApi.addOrUpdate(values),
    onSuccess: () => {
      message.success('操作成功')
      setModalOpen(false)
      setEditId(null)
      formInstance.resetFields()
      queryClient.invalidateQueries({ queryKey: ['orders'] })
    },
  })

  const deleteMutation = useMutation({
    mutationFn: (id: string) => productionApi.deleteById(id),
    onSuccess: () => {
      message.success('删除成功')
      queryClient.invalidateQueries({ queryKey: ['orders'] })
    },
  })

  const handleSearch = (values: Record<string, unknown>) => {
    setFilters(values)
    reset()
  }

  const handleReset = () => {
    setFilters({})
    reset()
  }

  const handleAdd = () => {
    setEditId(null)
    setModalOpen(true)
  }

  const handleEdit = (record: ProductionOrder) => {
    setEditId(record.id)
    setModalOpen(true)
  }

  const handleDelete = (record: ProductionOrder) => {
    deleteMutation.mutate(record.id)
  }

  const handleModalCancel = () => {
    setModalOpen(false)
    setEditId(null)
  }

  const handleFormFinish = (values: Record<string, unknown>) => {
    saveMutation.mutate({
      ...values,
      id: editId || undefined,
    })
  }

  const columns = [
    {
      title: '工单编码',
      dataIndex: 'orderCode',
      key: 'orderCode',
    },
    {
      title: '描述',
      dataIndex: 'orderDescription',
      key: 'orderDescription',
      ellipsis: true,
    },
    {
      title: '数量',
      dataIndex: 'qty',
      key: 'qty',
    },
    {
      title: '类型',
      dataIndex: 'orderType',
      key: 'orderType',
      render: (val: string) => {
        const t = orderTypeMap[val] || { text: val, color: 'default' }
        return <Tag color={t.color}>{t.text}</Tag>
      },
    },
    {
      title: '物料',
      dataIndex: 'materiel',
      key: 'materiel',
    },
    {
      title: '物料描述',
      dataIndex: 'materielDesc',
      key: 'materielDesc',
    },
    {
      title: '计划开始',
      dataIndex: 'planStartTime',
      key: 'planStartTime',
    },
    {
      title: '计划结束',
      dataIndex: 'planEndTime',
      key: 'planEndTime',
    },
    {
      title: '状态',
      dataIndex: 'statue',
      key: 'statue',
      render: (val: string) => {
        const s = statueMap[val] || { text: val, color: 'default' }
        return <Tag color={s.color}>{s.text}</Tag>
      },
    },
    {
      title: '操作',
      key: 'action',
      render: (_: unknown, record: ProductionOrder) => (
        <span>
          <Button type="link" size="small" onClick={() => handleEdit(record)}>
            编辑
          </Button>
          <Popconfirm title="确定要删除该工单吗？" onConfirm={() => handleDelete(record)}>
            <Button type="link" size="small" danger>
              删除
            </Button>
          </Popconfirm>
        </span>
      ),
    },
  ]

  return (
    <PageContainer>
      <SearchForm onSearch={handleSearch} onReset={handleReset} loading={isLoading}>
        <Form.Item name="orderCode">
          <Input placeholder="工单编码" />
        </Form.Item>
        <Form.Item name="materiel">
          <Input placeholder="物料编码" />
        </Form.Item>
      </SearchForm>

      <PageTable
        rowKey="id"
        columns={columns}
        dataSource={ensureArray(data?.records)}
        loading={isLoading}
        total={data?.total || 0}
        pagination={{
          current: pagination.current,
          pageSize: pagination.pageSize,
        }}
        onChange={onChange}
        toolbar={
          <PermissionGuard perm="order:add">
            <Button type="primary" icon={<PlusOutlined />} onClick={handleAdd}>
              新增
            </Button>
          </PermissionGuard>
        }
      />

      <ModalForm
        open={modalOpen}
        title={editId ? '编辑工单' : '新增工单'}
        formInstance={formInstance}
        onCancel={handleModalCancel}
        loading={saveMutation.isPending}
      >
        <OrderForm
          id={editId}
          formInstance={formInstance}
          onFinish={handleFormFinish}
        />
      </ModalForm>
    </PageContainer>
  )
}
