// mes/vue3/src/views/basedata/device-group/DeviceGroupForm.vue
<template>
  <FormDialog
    :model-value="modelValue"
    :title="isEdit ? '编辑编组' : '新增编组'"
    width="560px"
    :loading="loading"
    @update:model-value="(v) => emit('update:modelValue', v)"
    @submit="handleSubmit"
  >
    <el-form ref="formRef" :model="form" :rules="rules" label-width="88px">
      <el-form-item label="编组编码" prop="code">
        <el-input v-model="form.code" placeholder="如 G01" clearable />
      </el-form-item>
      <el-form-item label="编组名称" prop="name">
        <el-input v-model="form.name" placeholder="请输入编组名称" clearable />
      </el-form-item>
      <el-form-item label="描述" prop="descr">
        <el-input v-model="form.descr" type="textarea" :rows="3" placeholder="请输入描述" />
      </el-form-item>
    </el-form>
  </FormDialog>
</template>

<script setup lang="ts">
import { ref, reactive, computed, watch } from 'vue'
import type { FormInstance, FormRules } from 'element-plus'
import FormDialog from '@/components/FormDialog.vue'
import { buildGroupPayload } from '@/utils/device'
import type { SpDeviceGroup } from '@/types/basedata'

const props = defineProps<{
  modelValue: boolean
  /** null = 新增;Partial(有 id) = 编辑 */
  model: Partial<SpDeviceGroup> | null
  loading?: boolean
}>()

const emit = defineEmits<{
  'update:modelValue': [boolean]
  submit: [Partial<SpDeviceGroup>]
}>()

const formRef = ref<FormInstance>()
const isEdit = computed(() => !!props.model?.id)

const form = reactive<Partial<SpDeviceGroup>>({
  id: undefined,
  code: '',
  name: '',
  descr: undefined,
})

function resetForm() {
  form.id = undefined
  form.code = ''
  form.name = ''
  form.descr = undefined
}

watch(
  () => props.model,
  (val) => {
    if (val) Object.assign(form, { ...val })
    else resetForm()
  },
  { immediate: true },
)

const rules: FormRules = {
  code: [{ required: true, message: '请输入编组编码', trigger: 'blur' }],
  name: [{ required: true, message: '请输入编组名称', trigger: 'blur' }],
}

async function handleSubmit() {
  await formRef.value?.validate()
  emit('submit', buildGroupPayload({ ...form }))
}
</script>

// mes/frontend/src/pages/basedata/DeviceGroupForm.tsx
import { useEffect } from 'react'
import { Form, Input, Radio } from 'antd'
import type { FormInstance } from 'antd/es/form'
import type { SpDeviceGroup } from '@/types/device'

interface DeviceGroupFormProps {
  id?: string | null
  record?: SpDeviceGroup | null
  onFinish?: (values: any) => void
  formInstance: FormInstance
}

function DeviceGroupForm({ id, record, onFinish, formInstance }: DeviceGroupFormProps) {
  useEffect(() => {
    if (id && record) {
      formInstance.setFieldsValue(record)
    } else if (!id) {
      formInstance.resetFields()
    }
  }, [id, record, formInstance])

  return (
    <Form form={formInstance} layout="vertical" onFinish={onFinish}
      initialValues={{ deleted: '0' }}>
      <Form.Item name="code" label="编组代码" rules={[{ required: true, message: '请输入编组代码' }]}>
        <Input placeholder="请输入编组代码" />
      </Form.Item>
      <Form.Item name="name" label="编组名称" rules={[{ required: true, message: '请输入编组名称' }]}>
        <Input placeholder="请输入编组名称" />
      </Form.Item>
      <Form.Item name="descr" label="描述">
        <Input.TextArea rows={2} placeholder="请输入描述" />
      </Form.Item>
      <Form.Item name="deleted" label="状态" rules={[{ required: true }]}>
        <Radio.Group>
          <Radio value="0">正常</Radio>
          <Radio value="1">已删除</Radio>
          <Radio value="2">已禁用</Radio>
        </Radio.Group>
      </Form.Item>
    </Form>
  )
}

export default DeviceGroupForm
