// mes/vue3/src/components/EChart.vue
<template>
  <VChart class="echart" :option="option" autoresize :theme="undefined" />
</template>

<script setup lang="ts">
/**
 * 轻量 ECharts 封装(按需注册组件,控制体积)。
 * 配色由调用方通过 option 传入,以便随站点主题(浅/深)切换重算。
 */
import { use } from 'echarts/core'
import { CanvasRenderer } from 'echarts/renderers'
import { LineChart, BarChart, PieChart } from 'echarts/charts'
import {
  GridComponent,
  TooltipComponent,
  LegendComponent,
  TitleComponent,
} from 'echarts/components'
import VChart from 'vue-echarts'
import type { EChartsOption } from 'echarts'

use([
  CanvasRenderer,
  LineChart,
  BarChart,
  PieChart,
  GridComponent,
  TooltipComponent,
  LegendComponent,
  TitleComponent,
])

defineProps<{ option: EChartsOption }>()
</script>

<style scoped>
.echart {
  width: 100%;
  height: 100%;
}
</style>

// mes/frontend/apps/mes-new/src/components/EChart.tsx
import { useEffect, useRef } from 'react'
import * as echarts from 'echarts/core'
import { BarChart, LineChart, PieChart, GaugeChart } from 'echarts/charts'
import {
  GridComponent,
  TooltipComponent,
  LegendComponent,
  TitleComponent,
} from 'echarts/components'
import { CanvasRenderer } from 'echarts/renderers'
import type { EChartOption } from '@/pages/digitization/dashboardOptions'

echarts.use([
  BarChart,
  LineChart,
  PieChart,
  GaugeChart,
  GridComponent,
  TooltipComponent,
  LegendComponent,
  TitleComponent,
  CanvasRenderer,
])

interface EChartProps {
  option: EChartOption
  className?: string
}

/** 通用 ECharts 容器:容器尺寸自适应,卸载自动销毁。父级须给定高度。 */
export default function EChart({ option, className }: EChartProps) {
  const elRef = useRef<HTMLDivElement>(null)
  const chartRef = useRef<echarts.ECharts | null>(null)

  useEffect(() => {
    if (!elRef.current) return
    const chart = echarts.init(elRef.current)
    chartRef.current = chart
    const ro = new ResizeObserver(() => chart.resize())
    ro.observe(elRef.current)
    return () => {
      ro.disconnect()
      chart.dispose()
      chartRef.current = null
    }
  }, [])

  useEffect(() => {
    chartRef.current?.setOption(option as echarts.EChartsCoreOption, true)
  }, [option])

  return <div ref={elRef} className={className} />
}
