// mes/frontend/apps/mes-new/src/pages/order/production/OrderForm.tsx
import { useEffect } from 'react'
import { Controller, useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import {
  Input,
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
  Textarea,
  toast,
} from '@workspace/ui'
import { ClipboardList, Info } from 'lucide-react'
import FormDialog, { FormSection } from '@/components/FormDialog'
import FormField from '@/components/FormField'
import { useQuery$, useMutation$ } from '@/http/hooks'
import { invalidate } from '@/http/queryCache'
import { orderAddOrUpdate } from '@/api/order/order'
import { materilePage } from '@/api/basedata/materile'
import { flowList } from '@/api/technology/flow'
import { toDatetimeLocal, fromDatetimeLocal } from '@/utils/datetime'
import type { SpOrder } from '@/types/order'

const ORDER_TYPES = [
  { value: 'P', label: '批量' },
  { value: 'A', label: '验证' },
  { value: 'F', label: '返工' },
]

const schema = z.object({
  orderCode: z.string().min(1, '请输入工单编号'),
  orderDescription: z.string().optional(),
  qty: z.coerce.number({ invalid_type_error: '请输入数量' }).int('需为整数').min(1, '数量至少 1'),
  orderType: z.enum(['P', 'A', 'F']),
  materiel: z.string().min(1, '请选择物料'),
  materielDesc: z.string().optional(),
  flowId: z.string().optional(),
  planStartTime: z.string().optional(),
  planEndTime: z.string().optional(),
})

type FormValues = z.infer<typeof schema>

interface Props {
  open: boolean
  onOpenChange: (open: boolean) => void
  record?: SpOrder | null
}

export default function OrderForm({ open, onOpenChange, record }: Props) {
  const isEdit = !!record
  const { data: materials } = useQuery$(
    ['order', 'materials'],
    () => materilePage({ current: 1, size: 200 }),
    { enabled: open },
  )
  const { data: flows } = useQuery$(['order', 'flows'], () => flowList(), { enabled: open })
  const { mutate, loading } = useMutation$((dto: Partial<SpOrder>) => orderAddOrUpdate(dto))

  const {
    register,
    handleSubmit,
    control,
    reset,
    setValue,
    formState: { errors },
  } = useForm<FormValues>({
    resolver: zodResolver(schema),
    defaultValues: {
      orderCode: '', orderDescription: '', qty: 1, orderType: 'P',
      materiel: '', materielDesc: '', flowId: '', planStartTime: '', planEndTime: '',
    },
  })

  useEffect(() => {
    if (open) {
      reset({
        orderCode: record?.orderCode ?? '',
        orderDescription: record?.orderDescription ?? '',
        qty: record?.qty ?? 1,
        orderType: (record?.orderType as FormValues['orderType']) ?? 'P',
        materiel: record?.materiel ?? '',
        materielDesc: record?.materielDesc ?? '',
        flowId: record?.flowId ?? '',
        planStartTime: toDatetimeLocal(record?.planStartTime),
        planEndTime: toDatetimeLocal(record?.planEndTime),
      })
    }
  }, [open, record, reset])

  const onSubmit = handleSubmit(async (values) => {
    try {
      await mutate({
        id: record?.id,
        orderCode: values.orderCode,
        orderDescription: values.orderDescription ?? '',
        qty: values.qty,
        orderType: values.orderType,
        materiel: values.materiel,
        materielDesc: values.materielDesc ?? '',
        flowId: values.flowId ?? '',
        planStartTime: fromDatetimeLocal(values.planStartTime),
        planEndTime: fromDatetimeLocal(values.planEndTime),
        ...(isEdit ? { statue: record?.statue } : {}),
      })
      toast.success(isEdit ? '修改成功' : '新增成功')
      invalidate('["order","page"')
      onOpenChange(false)
    } catch {
      /* toast by interceptor */
    }
  })

  return (
    <FormDialog
      open={open}
      onOpenChange={onOpenChange}
      title={isEdit ? '编辑生产订单' : '新增生产订单'}
      description="维护生产工单(物料、工艺路线、计划时间)"
      icon={ClipboardList}
      onSubmit={onSubmit}
      submitting={loading}
      contentClassName="sm:max-w-2xl"
    >
      <FormSection title="基本信息" icon={Info} tag="必填">
        <div className="grid grid-cols-2 gap-4">
          <FormField label="工单编号" htmlFor="o-code" required error={errors.orderCode?.message}>
            <Input id="o-code" aria-invalid={!!errors.orderCode} {...register('orderCode')} />
          </FormField>
          <FormField label="数量" htmlFor="o-qty" required error={errors.qty?.message}>
            <Input id="o-qty" type="number" min={1} aria-invalid={!!errors.qty} {...register('qty')} />
          </FormField>
        </div>
        <div className="grid grid-cols-2 gap-4">
          <FormField label="订单类型" required>
            <Controller
              control={control}
              name="orderType"
              render={({ field }) => (
                <Select value={field.value} onValueChange={field.onChange}>
                  <SelectTrigger className="w-full"><SelectValue /></SelectTrigger>
                  <SelectContent>
                    {ORDER_TYPES.map((t) => <SelectItem key={t.value} value={t.value}>{t.label}</SelectItem>)}
                  </SelectContent>
                </Select>
              )}
            />
          </FormField>
          <FormField label="物料" required error={errors.materiel?.message}>
            <Controller
              control={control}
              name="materiel"
              render={({ field }) => (
                <Select
                  value={field.value || undefined}
                  onValueChange={(v) => {
                    field.onChange(v)
                    const m = (materials?.records ?? []).find((x) => x.materiel === v)
                    setValue('materielDesc', m?.materielDesc ?? '')
                  }}
                >
                  <SelectTrigger className="w-full"><SelectValue placeholder="请选择物料" /></SelectTrigger>
                  <SelectContent>
                    {(materials?.records ?? []).map((m) => (
                      <SelectItem key={m.materiel} value={m.materiel}>{m.materiel} - {m.materielDesc}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              )}
            />
          </FormField>
        </div>
        <FormField label="工艺路线" htmlFor="o-flow">
          <Controller
            control={control}
            name="flowId"
            render={({ field }) => (
              <Select value={field.value || undefined} onValueChange={field.onChange}>
                <SelectTrigger id="o-flow" className="w-full"><SelectValue placeholder="请选择工艺路线" /></SelectTrigger>
                <SelectContent>
                  {(flows ?? []).map((f) => (
                    <SelectItem key={f.id} value={f.id}>{f.flow} - {f.flowDesc}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            )}
          />
        </FormField>
        <FormField label="工单描述" htmlFor="o-desc">
          <Textarea id="o-desc" {...register('orderDescription')} />
        </FormField>
      </FormSection>
      <FormSection title="计划时间" icon={Info} tag="选填">
        <div className="grid grid-cols-2 gap-4">
          <FormField label="计划开始" htmlFor="o-start">
            <Input id="o-start" type="datetime-local" {...register('planStartTime')} />
          </FormField>
          <FormField label="计划结束" htmlFor="o-end">
            <Input id="o-end" type="datetime-local" {...register('planEndTime')} />
          </FormField>
        </div>
      </FormSection>
    </FormDialog>
  )
}

// mes/vue3/src/views/order/release/OrderForm.vue
<template>
  <FormDialog
    :model-value="modelValue"
    :title="isEdit ? '编辑工单' : '新增工单'"
    width="640px"
    :loading="loading"
    @update:model-value="(v) => emit('update:modelValue', v)"
    @submit="handleSubmit"
  >
    <el-form :model="form" label-width="96px">
      <el-row :gutter="16">
        <el-col :span="12">
          <el-form-item label="工单编号">
            <el-input v-model="form.orderCode" placeholder="请输入工单编号" clearable />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="工单类型">
            <el-select v-model="form.orderType" placeholder="请选择" clearable style="width: 100%">
              <el-option label="量产 (P)" value="P" />
              <el-option label="验证 (A)" value="A" />
              <el-option label="返工 (F)" value="F" />
            </el-select>
          </el-form-item>
        </el-col>
      </el-row>

      <el-row :gutter="16">
        <el-col :span="12">
          <el-form-item label="物料">
            <el-select
              v-model="form.materiel"
              placeholder="请选择物料"
              clearable
              filterable
              style="width: 100%"
              @change="onMaterielChange"
            >
              <el-option
                v-for="m in materials"
                :key="m.id"
                :label="`${m.materiel ?? ''} ${m.materielDesc ?? ''}`"
                :value="m.materiel!"
              />
            </el-select>
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="数量">
            <el-input-number
              v-model="form.qty"
              :min="1"
              :precision="0"
              controls-position="right"
              style="width: 100%"
            />
          </el-form-item>
        </el-col>
      </el-row>

      <el-form-item label="物料描述">
        <el-input v-model="form.materielDesc" placeholder="选物料后自动带出，可改" clearable />
      </el-form-item>

      <el-form-item label="工艺路线">
        <el-select v-model="form.flowId" placeholder="请选择工艺路线" clearable filterable style="width: 100%">
          <el-option v-for="f in flows" :key="f.id" :label="`${f.flow} ${f.flowDesc ?? ''}`" :value="f.id" />
        </el-select>
      </el-form-item>

      <el-row :gutter="16">
        <el-col :span="12">
          <el-form-item label="计划开始">
            <el-date-picker
              v-model="form.planStartTime"
              type="datetime"
              value-format="YYYY-MM-DD HH:mm:ss"
              placeholder="计划开始时间"
              style="width: 100%"
            />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="计划结束">
            <el-date-picker
              v-model="form.planEndTime"
              type="datetime"
              value-format="YYYY-MM-DD HH:mm:ss"
              placeholder="计划结束时间"
              style="width: 100%"
            />
          </el-form-item>
        </el-col>
      </el-row>

      <el-form-item label="工单描述">
        <el-input v-model="form.orderDescription" type="textarea" :rows="2" placeholder="选填" />
      </el-form-item>
    </el-form>
  </FormDialog>
</template>

<script setup lang="ts">
import { reactive, computed, watch } from 'vue'
import { ElMessage } from 'element-plus'
import FormDialog from '@/components/FormDialog.vue'
import { useRequest } from '@/composables/useRequest'
import { materilePage } from '@/api/basedata/materile'
import { flowList } from '@/api/technology/flow'
import { buildOrderPayload, validateOrder } from '@/utils/order'
import type { SpOrder } from '@/types/order'
import type { SpMaterile } from '@/types/basedata'

const props = defineProps<{
  modelValue: boolean
  /** null = 新增;Partial(有 id) = 编辑 */
  model: Partial<SpOrder> | null
  loading?: boolean
}>()

const emit = defineEmits<{
  'update:modelValue': [boolean]
  submit: [Partial<SpOrder>]
}>()

const isEdit = computed(() => !!props.model?.id)
const form = reactive<Partial<SpOrder>>({})

// 物料下拉(全量取前 200 条,filterable 本地过滤)
const { data: matPage } = useRequest(() => materilePage({ current: 1, size: 200 }), { immediate: true })
const materials = computed<SpMaterile[]>(() => matPage.value?.records ?? [])

// 工艺路线下拉(全量 GET)
const { data: flows } = useRequest(() => flowList(), { immediate: true, initialData: [] })

watch(
  () => props.modelValue,
  (open) => {
    if (open) {
      const m = props.model ?? {}
      Object.keys(form).forEach((k) => delete (form as Record<string, unknown>)[k])
      Object.assign(form, { qty: 1, ...m })
    }
  },
  { immediate: true },
)

function onMaterielChange(code: string) {
  const hit = materials.value.find((m) => m.materiel === code)
  if (hit) form.materielDesc = hit.materielDesc
}

function handleSubmit() {
  const err = validateOrder(form)
  if (err) {
    ElMessage.warning(err)
    return
  }
  emit('submit', buildOrderPayload(form))
}
</script>
